### ISSUE TITLE
Support for token_link parameter?

### ISSUE THREAD

**Issue by huntermotte** [mike-roberts/ngx-plaid-link#17]
Hi, do you have any plans to add the token_link parameter to this component? (https://plaid.com/docs/#create-link-token). It looks like as of July 2020 new Plaid accounts will require this authenticate. Happy to help merge a PR to get this put through if no one is working on it yet.

**Comment by becky-intelletive** [comment]
I would also love that. Along those same lines, the public_key config initializer is being deprecated. I have a new Plaid account that has no public_key, only a client_id and a client_secret. This library becomes useless to me if it doesn't support authentication using client_id and client_secret parameters instead of publicKey.

https://plaid.com/docs/upgrade-to-link-tokens/

**Comment by psullivan-jexisys** [comment]
Anyone have word on this, by chance?

**Comment by brobusf21** [comment]
Any updates regarding this request?

Currently receiving this error after manually obtaining a link_token and passing into the PUBLICKEY:

`LazyLink.js:2 Error: Invalid key and token: key and token cannot both be missing.`

**Comment by mike-roberts** [comment]
Hi, I'd like to get this in ASAP so you all can use this, but I don't have an account that uses link_tokens. Anyone willing to be a guinea pig and test out a branch/PR that I open?

**Comment by mike-roberts** [comment]
Alright, the branch `link-token-support` and this PR https://github.com/mike-roberts/ngx-plaid-link/pull/22 should support link_tokens. Anyone want to give it a try? If it works I'll get it merged and get a new npm release out.

**Comment by mike-roberts** [comment]
this has been published in 1.0.3
